### ISSUE TITLE
Change offset after initial script call.

### ISSUE THREAD

**Issue by ghost** [JamyGolden/PlusAnchor#7]
Hi, great plugin!

I wanted to change the offset option after the initial call. I have tried unloading after animate but with no luck. Basically I have a relative header that becomes fixed when it hits the top of the page when scrolling. So when the header is relative the offset is -150px and when its fixed the offset is -75px. 

Is there a way to do this?

Thanks in advance, 
John.

**Comment by JamyGolden** [comment]
The easiest way to do this would be ton run `$('body').plusAnchor(false, false);` to disable the plugin and then run `$('body').plusAnchor({...})` again with the desired options.
